### ISSUE TITLE
Support imports containing slashes 

### ISSUE THREAD

**Issue by tibdex** [stevenbenisek/rollup-plugin-auto-external#7]
Hi Steven,

Currently, if `lodash` is a dependency, this plugin considers `import _ from 'lodash'` as external but not `import fp from 'lodash/fp'`.

It would work if you were to replace: 

https://github.com/stevenbenisek/rollup-plugin-auto-external/blob/c320b49658ea7480a25fcf99c6f84fa36e5bd730/index.js#L37-L46

by:

```javascript
external = id => {
  if (
    (typeof opts.external === "function" && opts.external(id)) ||
    (Array.isArray(opts.external) && opts.external.includes(id))
  ) {
    return true;
  }

  const packageName = id.split("/")[0];

  return ids.includes(packageName);
};
```

I wanted to make a PR to propose this addition but it requires changing most of the test suite because the `external` option would always be a function.
Do you agree that `import fp from 'lodash/fp'` should be considered external too?
If I submit the PR, would you consider merging it?

Thanks

**Comment by mmermerkaya** [comment]
Your solution wouldn't work for dependencies that have a slash in their name, such as `@angular/core` or `@firebase/messaging`.

What about this?
```
ids.some(dep => id === dep || id.startsWith(`${dep}/`))
```

**Comment by tibdex** [comment]
> Your solution wouldn't work for dependencies that have a slash in their name.

You're right, I forgot about them. Since, dependencies with a slash in their name are what npm calls [scope packages](https://docs.npmjs.com/misc/scope), we could change the code to:

```javascript
external = id => {
  if (
    (typeof opts.external === "function" && opts.external(id)) ||
    (Array.isArray(opts.external) && opts.external.includes(id))
  ) {
    return true;
  }

  const isScopedPackage = id.startsWith('@');
  const packageName = id.split("/").slice(0, isScopedPackage ? 2 : 1).join('/');

  return ids.includes(packageName);
};
```

**Comment by marvinroger** [comment]
Any updates on this?

**Comment by NathanielHill** [comment]
Any word on this moving forward? Does the plugin currently not work with scoped packages?

@stevenbenisek

**Comment by stevenbenisek** [comment]
Long overdue, but you can expect a new version supporting cherry picked modules (e.g: `lodash/fp`) in the next couple of days. Scoped packages will work as expected. Thank you everyone for your patience and input.

**Comment by NathanielHill** [comment]
@stevenbenisek Awesome, I'll give this plugin another try when this issue gets closed :+1: 

The concept seems perfect for many shared library/component applications :ok_hand:

**Comment by stevenbenisek** [comment]
:tada: There's an alpha release available if anyone's interested in giving it a go: 

```
npm install rollup-plugin-auto-external@alpha
```

**Comment by rehos** [comment]
I have been testing the alpha release 3.0.0-alpha.0, but it doesn't work for imports from the [aws-sdk](https://github.com/aws/aws-sdk-js).

In our fork I have added 3 test cases that mimic the way the aws-sdk is structured. See https://github.com/everdune/rollup-plugin-auto-external/commit/e9121bde9e072ea25a4b8075033ea7e108e37a84 (sorry for typo in commit message).

I also fixed it but I didn't create a pull request for it yet, because the fix isn't based on resolved paths anymore (it is based on https://github.com/stevenbenisek/rollup-plugin-auto-external/issues/7#issuecomment-382417376). However all existing tests are also passing with this fix. Do you have a test case were the use of resolved paths is mandatory? You can see the fix that is working for us here https://github.com/everdune/rollup-plugin-auto-external/commit/105e855aa6c9cf8d40589de808ae5a29ed434cdd
